# version: "3"
# services:
#   api:
#     build: .
#     ports:
#       - 8000:8000
    
#     environment:
#       - DATABASE_HOSTNAME=fastapi
#       - DATABASE_PORT=5432
#       - DATABASE_PASSWORD=postgres
#       - DATABASE_NAME=fastapi
#       - DATABASE_USERNAME=postgres
#       - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
#       - ALGORITHM=HS256
#       - ACCESS_TOKEN_EXPIRE_MINUTES=30
#   postgres:
#     image: postgres
#     container_name: fastapi
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=fastapi
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres-db:


version: "3"
services:
  api:
    image: amanmittal04/fastapi:0.1
    container_name: fastapi
    ports:
      - 8000:8000
    
    environment:
      - DATABASE_HOSTNAME=fastapi
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - EMAIL=amanmittal0210@gmail.com
      - PASSWORD=pedqtuwfrandneko
  postgres:
    image: postgres
    container_name: fastapi_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: