"""Add expiration_time column to Post table

Revision ID: 14492945b8dd
Revises: a2e8f3a5e70d
Create Date: 2023-05-16 13:02:57.480169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14492945b8dd'
down_revision = 'a2e8f3a5e70d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column(
        'expiration_time', sa.Integer, nullable=False, server_default='1'))

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'expiration_time')

    pass
    # ### end Alembic commands ###
